// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VHSMovies.Infraestructure;

#nullable disable

namespace VHSMovies.Infraestructure.Migrations
{
    [DbContext(typeof(DbContextClass))]
    [Migration("20241222192308_test_new_models")]
    partial class test_new_models
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Cast", b =>
                {
                    b.Property<int>("TitleId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("TitleId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("casts", (string)null);
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.PersonRole", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("PersonId", "Role");

                    b.ToTable("person_role", (string)null);
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer");

                    b.Property<string>("TitleExternalId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TitleExternalUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TitleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TitleId");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Reviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("reviewers", (string)null);
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.TVShowSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodesQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("TVShowId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TVShowId");

                    b.ToTable("tvshow_seasons", (string)null);
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("titles", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.TitleGenre", b =>
                {
                    b.Property<int>("TitleId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("TitleId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("titles_genres", (string)null);
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Movie", b =>
                {
                    b.HasBaseType("VHSMovies.Domain.Domain.Entity.Title");

                    b.Property<decimal?>("Duration")
                        .HasColumnType("numeric");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.TVShow", b =>
                {
                    b.HasBaseType("VHSMovies.Domain.Domain.Entity.Title");

                    b.ToTable("tvshows", (string)null);
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Cast", b =>
                {
                    b.HasOne("VHSMovies.Domain.Domain.Entity.Person", "Person")
                        .WithMany("Titles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VHSMovies.Domain.Domain.Entity.Title", "Title")
                        .WithMany("Cast")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.PersonRole", b =>
                {
                    b.HasOne("VHSMovies.Domain.Domain.Entity.Person", "Person")
                        .WithMany("Roles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Review", b =>
                {
                    b.HasOne("VHSMovies.Domain.Domain.Entity.Reviewer", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VHSMovies.Domain.Domain.Entity.Title", "Title")
                        .WithMany("Reviews")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.TVShowSeason", b =>
                {
                    b.HasOne("VHSMovies.Domain.Domain.Entity.TVShow", null)
                        .WithMany("Seasons")
                        .HasForeignKey("TVShowId");
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.TitleGenre", b =>
                {
                    b.HasOne("VHSMovies.Domain.Domain.Entity.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VHSMovies.Domain.Domain.Entity.Title", "Title")
                        .WithMany("Genres")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Movie", b =>
                {
                    b.HasOne("VHSMovies.Domain.Domain.Entity.Title", null)
                        .WithOne()
                        .HasForeignKey("VHSMovies.Domain.Domain.Entity.Movie", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.TVShow", b =>
                {
                    b.HasOne("VHSMovies.Domain.Domain.Entity.Title", null)
                        .WithOne()
                        .HasForeignKey("VHSMovies.Domain.Domain.Entity.TVShow", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Person", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Reviewer", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.Title", b =>
                {
                    b.Navigation("Cast");

                    b.Navigation("Genres");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("VHSMovies.Domain.Domain.Entity.TVShow", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
