services:
  vhsmovies.website:
    image: ${DOCKER_REGISTRY-}vhsmovieswebsite
    container_name: vhsmovies.website
    build:
      context: .
      dockerfile: VHSMovies.Website/Dockerfile
    environment:
       - ApiUrl__DefaultApi=http://vhsmovies.api:5000
    ports:
    - "8080:80"
    - "443:443"
    networks:
      - vhsmovies_network

  vhsmovies.api:
    image: ${DOCKER_REGISTRY-}vhsmoviesapi
    container_name: vhsmovies.api
    build:
      context: .
      dockerfile: VHSMovies.Api/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - vhsmovies.database
    networks:
      - vhsmovies_network

  vhsmovies.database:
     image: postgres:latest
     container_name: vhsmovies.database
     environment:
       - POSTGRES_DB=vhsmovies
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
     volumes:
       - ./.containers/vhsmovies-db:/var/lib/postgresql/data
     ports:
       - "5432:5432"
     networks:
      - vhsmovies_network

networks:
  vhsmovies_network:
    driver: bridge