name: Deploy to Railway - API and Website

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      # Deploy API
      - name: Deploy VHSMovies.Api
        working-directory: src/VHSMovies.Api
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROJECT_TOKEN }}
        run: |
          railway link ${{ secrets.RAILWAY_PROJECT_ID_API }} --yes
          railway up --service api-service --detach

      # Deploy Website
      - name: Deploy VHSMovies.Website
        working-directory: src/VHSMovies.Website
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROJECT_TOKEN }}
        run: |
          railway link ${{ secrets.RAILWAY_PROJECT_ID_WEB }} --yes
          railway up --service web-service --detach
