name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  continuous-integrations:
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v3
    
        - name: Docker Login
          uses: docker/login-action@v3.4.0
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_USER_PASSWORD }}
    
        - name: Build and Push Docker images
          uses: docker/build-push-action@v3.2.0
          with:
            context: .
            file: .
            push: true
            tags: |
              victorhenrique011/vhsmovies-api:v1
              victorhenrique011/vhsmovies-api:latest
