name: Build

on: 
  push:
    branches: [main]
    paths:
      - 'src/VHSMovies.Api.Integration/**'
      - 'src/VHSMovies.Website/**'
      - 'tests/VHSMovies.Tests.Website/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0
      - name: Restore Dependencies
        run: dotnet restore ./src/VHSMovies.Website/VHSMovies.Website.csproj
      - name: Build Project
        run: dotnet build ./src/VHSMovies.Website/VHSMovies.Website.csproj --no-restore

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Restore Test Dependencies
        run: dotnet restore ./tests/VHSMovies.Tests.Website/VHSMovies.Tests.Website.csproj

      - name: Unit Tests, Integration Tests and E2E Tests
        run: dotnet test ./tests/VHSMovies.Tests.Website/VHSMovies.Tests.Website.csproj --no-build --verbosity normal

  release-website-container:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}

      - name: Build and push Docker image (Website)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./src/VHSMovies.Website/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/vhsmovies-website:v1
            ${{ secrets.DOCKER_USER }}/vhsmovies-website:latest